version: "3"

services:
  fidelizacion:
    container_name: fidelizacion
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    ports:
      - 3000:80
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8000:8000
